### PR TITLE
[Pal/Linux] Disable host-level ASLR in PAL Linux

### PR DESCRIPTION
**Pull request by boryspoplawski**
## Description of the changes 
Graphene fork() emulation does fork()+execve() on the host system which effectively remats PAL executable to a new address if ASLR is on. The new location could collide with other mappings that are later on sent to the child process via checkpointing mechanism (user mapped regions).

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2597)

### CODE REVIEW

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2597)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2597#-Mfo5S-g8yLsCbuexzjG:-Mfo5S-i8H4somjvKwOo:b29xydp) (no related file):*
Looks like docker disables most usages of `personality` syscall (except for uname26 and linu32), so this won't work in default docker setup. Why they disallow disabling ASLR per process is beyond my understanding...

---

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2597)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2597#-Mfo5S-g8yLsCbuexzjG:-Mfq9NbBEPRps6btybMt:b33yn3l) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Looks like docker disables most usages of `personality` syscall (except for uname26 and linu32), so this won't work in default docker setup. Why they disallow disabling ASLR per process is beyond my understanding...
</blockquote></details>

More context on `personality` in Docker:
- https://github.com/ros-infrastructure/buildfarm_deployment/issues/176
- https://github.com/ros-infrastructure/buildfarm_deployment/pull/194
- https://github.com/SimonKagstrom/kcov/issues/151#issuecomment-249284631

So yes, Docker by default disables a lot of `personality` usages. One can submit another seccomp config to Docker like this: `docker run --security-opt seccomp=unconfined` (or your custom seccomp config like in link 2).

But I am against this. This adds unnecessary complexity to Docker invocations. And given that many users want to run Graphene in Docker (by using our GSC tool), this just doesn't sound reasonable to me.

---

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2597)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2597#-Mfo5S-g8yLsCbuexzjG:-Mg50jg5ChcRMHgRBzOq:b2j4zgt) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

More context on `personality` in Docker:
- https://github.com/ros-infrastructure/buildfarm_deployment/issues/176
- https://github.com/ros-infrastructure/buildfarm_deployment/pull/194
- https://github.com/SimonKagstrom/kcov/issues/151#issuecomment-249284631

So yes, Docker by default disables a lot of `personality` usages. One can submit another seccomp config to Docker like this: `docker run --security-opt seccomp=unconfined` (or your custom seccomp config like in link 2).

But I am against this. This adds unnecessary complexity to Docker invocations. And given that many users want to run Graphene in Docker (by using our GSC tool), this just doesn't sound reasonable to me.
</blockquote></details>

As discussed in another PR #2595, this PR with `personality()` looks like a better, less hacky option.

I verified that it fixes #2589. I would prefer a better commit message (probably martially taken from my #2595), but I suggest we proceed with this PR.

As mentioned, we should add `--security-opt seccomp=unconfined` to our Docker config. In particular, here: https://github.com/oscarlab/graphene/blob/3182ca948c6712631a3ac9bf8983b8103351c9a9/.ci/lib/config-docker.jenkinsfile#L5. @boryspoplawski Could you add this to see if our Jenkins CI works with this? It worked for me locally.

At some point, when we update GSC to point to this commit, we'll need to modify its `docker run` commands / documentation too.

---

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2597)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2597#-Mfo5S-g8yLsCbuexzjG:-Mg5pg0-0QYW2OFlV6qh:b1fohwc) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

As discussed in another PR #2595, this PR with `personality()` looks like a better, less hacky option.

I verified that it fixes #2589. I would prefer a better commit message (probably martially taken from my #2595), but I suggest we proceed with this PR.

As mentioned, we should add `--security-opt seccomp=unconfined` to our Docker config. In particular, here: https://github.com/oscarlab/graphene/blob/3182ca948c6712631a3ac9bf8983b8103351c9a9/.ci/lib/config-docker.jenkinsfile#L5. @boryspoplawski Could you add this to see if our Jenkins CI works with this? It worked for me locally.

At some point, when we update GSC to point to this commit, we'll need to modify its `docker run` commands / documentation too.
</blockquote></details>

I could also write our own profile (I guess just copy the default docker one and modify it).

---

**Review by boryspoplawski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2597)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[Pal/src/host/Linux/db_main.c, line 186 at r1](https://reviewable.io/reviews/oscarlab/graphene/2597#-Mg5qOeoDVC-CNuLSBOs:-Mg5qOeoDVC-CNuLSBOt:b-8i7efb) ([raw file](https://github.com/oscarlab/graphene/blob/765a35671b9bbc42a349a74b782f98187ee31fb9/Pal/src/host/Linux/db_main.c#L186)):*
> ```C
> 
>     if (first_process) {
>         ret = INLINE_SYSCALL(personality, 1, 0xffffffff);
> ```

TODO: add a `u` suffix.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2597)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2597#-Mfo5S-g8yLsCbuexzjG:-Mg5xeetC42fOG3_uyeA:b-6u4zkm) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I could also write our own profile (I guess just copy the default docker one and modify it).
</blockquote></details>

Also good. The default Docker profile is here: https://github.com/docker/docker/blob/master/profiles/seccomp/default.json

---

**Comment by boryspoplawski** [comment]
Superseded by https://github.com/gramineproject/gramine/pull/89

**Pull request closed without merging**
