### PR TITLE
[Docs] Add repo migration note to the README

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

This will be probably the last PR merged in this repo :) CU at https://github.com/gramineproject/gramine!

## How to test this PR? 

Render the new text using GitHub Markdown renderer.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2683)

### CODE REVIEW

**Review by boryspoplawski — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2683)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[README.rst, line 3 at r1](https://reviewable.io/reviews/gramineproject/graphene/2683#-Mj-w9pYEQcVKGQE1ccM:-Mj-w9pZ5dWzfrLPKepv:b-c2je95) ([raw file](https://github.com/gramineproject/graphene/blob/79c661e21b8074850619e81dcd85da949df824a8/README.rst#L3)):*
> ```reStructuredText
> ********************************************************************************
> 
> **NOTE:** Graphene project was renamed to Gramine and moved to a new location:
> ```

Could we make this bigger, maybe even bigger than h1 (`#`) ?

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2683)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[README.rst, line 3 at r1](https://reviewable.io/reviews/gramineproject/graphene/2683#-Mj-w9pYEQcVKGQE1ccM:-Mj-yeGAE-tW55Q8yFa8:b-1rfblh) ([raw file](https://github.com/gramineproject/graphene/blob/79c661e21b8074850619e81dcd85da949df824a8/README.rst#L3)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Could we make this bigger, maybe even bigger than h1 (`#`) ?
</blockquote></details>

I don't think we can make it bigger in a nice way. But what about marking all this text as bold? Also, maybe add two horizontal lines instead of one on each side.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2683)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[README.rst, line 3 at r1](https://reviewable.io/reviews/gramineproject/graphene/2683#-Mj-w9pYEQcVKGQE1ccM:-Mj-yvaFClwQQ8A5g1dB:b-8dyzoa) ([raw file](https://github.com/gramineproject/graphene/blob/79c661e21b8074850619e81dcd85da949df824a8/README.rst#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't think we can make it bigger in a nice way. But what about marking all this text as bold? Also, maybe add two horizontal lines instead of one on each side.
</blockquote></details>

Actually, after we mark the repo as Archived, this text will become quite visible (people will scroll to check the README when they see "Archived")

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2683)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[README.rst, line 3 at r1](https://reviewable.io/reviews/gramineproject/graphene/2683#-Mj-w9pYEQcVKGQE1ccM:-Mj0-SEY7LCI-33NWqze:b-88aev8) ([raw file](https://github.com/gramineproject/graphene/blob/79c661e21b8074850619e81dcd85da949df824a8/README.rst#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, after we mark the repo as Archived, this text will become quite visible (people will scroll to check the README when they see "Archived")
</blockquote></details>

I would add a header:
```
#################################
PROJECT MOVED TO A NEW REPOSITORY
#################################
```
or something similar

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2683)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[README.rst, line 3 at r1](https://reviewable.io/reviews/gramineproject/graphene/2683#-Mj-w9pYEQcVKGQE1ccM:-Mj00H2n-99LUXTrrXSI:bwj29kj) ([raw file](https://github.com/gramineproject/graphene/blob/79c661e21b8074850619e81dcd85da949df824a8/README.rst#L3)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I would add a header:
```
#################################
PROJECT MOVED TO A NEW REPOSITORY
#################################
```
or something similar
</blockquote></details>

What about now?

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2683)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[README.rst, line 3 at r1](https://reviewable.io/reviews/gramineproject/graphene/2683#-Mj-w9pYEQcVKGQE1ccM:-Mj00VD-AuwA1NEIKK1d:b-sjfzyz) ([raw file](https://github.com/gramineproject/graphene/blob/79c661e21b8074850619e81dcd85da949df824a8/README.rst#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What about now?
</blockquote></details>

I would remove the line from the top, but if others are fine with it I won't block.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2683)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[README.rst, line 3 at r1](https://reviewable.io/reviews/gramineproject/graphene/2683#-Mj-w9pYEQcVKGQE1ccM:-Mj03nLL-zY0feoobHul:bhsmltq) ([raw file](https://github.com/gramineproject/graphene/blob/79c661e21b8074850619e81dcd85da949df824a8/README.rst#L3)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I would remove the line from the top, but if others are fine with it I won't block.
</blockquote></details>

I like the line at the top. But I also would like to make this whole text bold. Could we try it?

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2683)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @dimakuv)

___
*[README.rst, line 3 at r1](https://reviewable.io/reviews/gramineproject/graphene/2683#-Mj-w9pYEQcVKGQE1ccM:-Mj4hYv4DizKSMe8104Y:b-kdfmq0) ([raw file](https://github.com/gramineproject/graphene/blob/79c661e21b8074850619e81dcd85da949df824a8/README.rst#L3)):*
I also like the line.

> Could we try it?

You know you can test such things yourself? ;) https://github.com/gramineproject/graphene/edit/master/README.rst (and just preview)

I tried bolding the whole text and I prefer the current version. Also, note that it will be more visible after archiving the repo, as there will be a lot of signs showing that it's archived.

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2683)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @boryspoplawski)

___
*[README.rst, line 3 at r1](https://reviewable.io/reviews/gramineproject/graphene/2683#-Mj-w9pYEQcVKGQE1ccM:-Mj4jroBE-BVTFik4f6p:b-p87pl2) ([raw file](https://github.com/gramineproject/graphene/blob/79c661e21b8074850619e81dcd85da949df824a8/README.rst#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I also like the line.

> Could we try it?

You know you can test such things yourself? ;) https://github.com/gramineproject/graphene/edit/master/README.rst (and just preview)

I tried bolding the whole text and I prefer the current version. Also, note that it will be more visible after archiving the repo, as there will be a lot of signs showing that it's archived.
</blockquote></details>

OK. I am fine with this version.

**Comment by mkow** [comment]
Jenkins, retest this please

**Review by boryspoplawski — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2683)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by mkow** [comment]
Jenkins, retest this please (Jenkins died after the migration, we're still fixing it...)

**Comment by mkow** [comment]
Jenkins, retest this please

**Comment by mkow** [comment]
Jenkins, retest this please

**Pull request merged**
