### PR TITLE
[Pal/Linux] Assign an ephemeral port if port 0 was specified in `udp_bind`

### LINKED ISSUE #2291: sendmmsg fails to send multiple messages on a socket returns error EINVAL
## Description of the problem
sendmmsg - It is used to send multiple message on a socket.
sendmmsg01 tests fails in do_sendmsg while doing DkStreamWrite which  write to stream at absolute offset. The function returns 4 as a unix error which is 22 in linux(EINVAL)

## Expected results
/root/Graphene_Master/LibOS/shim/test/ltp/src/lib/tst_buffers.c:55: TINFO: Test is using guarded buffers
/root/Graphene_Master/LibOS/shim/test/ltp/src/lib/tst_test.c:1250: TINFO: Timeout per run is 0h 05m 00s
/root/Graphene_Master/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/sendmmsg/sendmmsg01.c:113: TINFO: Testing variant: vDSO or syscall with libc spec
/root/Graphene_Master/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/sendmmsg/sendmmsg01.c:74: TPASS: First message received successfully
/root/Graphene_Master/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/sendmmsg/sendmmsg01.c:79: TPASS: Second message received successfully
/root/Graphene_Master/LibOS/shim/test/ltp/src/lib/tst_test.c:1250: TINFO: Timeout per run is 0h 05m 00s
/root/Graphene_Master/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/sendmmsg/sendmmsg01.c:113: TINFO: Testing variant: syscall with old kernel spec
/root/Graphene_Master/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/sendmmsg/sendmmsg01.c:74: TPASS: First message received successfully
/root/Graphene_Master/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/sendmmsg/sendmmsg01.c:79: TPASS: Second message received successfully

Summary:
passed   4
failed   0
skipped  0
warnings 0

## Actual results
/root/Graphene_Master/LibOS/shim/test/ltp/src/lib/tst_buffers.c:55: TINFO: Test is using guarded buffers
/root/Graphene_Master/LibOS/shim/test/ltp/src/lib/tst_test.c:1250: TINFO: Timeout per run is 0h 05m 00s
/root/Graphene_Master/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/sendmmsg/sendmmsg01.c:113: TINFO: Testing variant: vDSO or syscall with libc spec
/root/Graphene_Master/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/sendmmsg/sendmmsg01.c:48: TFAIL: sendmmsg() failed: EINVAL (22)
/root/Graphene_Master/LibOS/shim/test/ltp/src/lib/tst_test.c:1250: TINFO: Timeout per run is 0h 05m 00s
/root/Graphene_Master/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/sendmmsg/sendmmsg01.c:113: TINFO: Testing variant: syscall with old kernel spec
/root/Graphene_Master/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/sendmmsg/sendmmsg01.c:48: TFAIL: sendmmsg() failed: EINVAL (22)

Summary:
passed   0
failed   2
skipped  0
warnings 0

### PR DESCRIPTION
**Pull request by sahason**
Signed-off-by: Sonali Saha <sonali.saha@intel.com>

## Description of the changes 
Fixed the issue of an ephemeral port is not allocated when port number in a socket address is specified as 0 when calling bind.
Fixes #2291

## How to test this PR? 
Follow the steps to reproduce mentioned in issue #2291.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2678)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2678)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @sahason)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2678#-Miu8DQFDfWVzILUU5NB:-Miu8DQFDfWVzILUU5NC:bymeckh) (no related file):*
Can you enable `sendmmsg01` (and potentially `sendmsg01`) LTP test now, with this fix? For this, you need to remove the following lines in the LTP config: https://github.com/oscarlab/graphene/blob/master/LibOS/shim/test/ltp/ltp.cfg#L1892-L1894

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2678#-Miu9YhaDauSy_PmYdvt:-Miu9YhaDauSy_PmYdvu:bqcmcoh) (no related file):*
From what I see, Linux-SGX PAL already has this logic of getting the port and assigning it to the relevant `addr` data struct. Is my understanding correct? The only place where this was missing is this UDP-bind function?

---
___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/oscarlab/graphene/2678#-Miu8QXL1D87c9FzTwQu):*
I would suggest a rewording like this:
```
[Pal/Linux] Assign an ephemeral port if port 0 was specified in `udp_bind`

This is already done in `tcp_listen` via a call to `getsockname()`. Do the same
for UDP sockets.
```
___
*[Pal/src/host/Linux/db_sockets.c, line 616 at r1](https://reviewable.io/reviews/oscarlab/graphene/2678#-Miu82ly2TE0oPGMS1tw:-Miu82ly2TE0oPGMS1tx:bljwp6x) ([raw file](https://github.com/oscarlab/graphene/blob/4c96b186e0100ba21068b44a24446c73000841ea/Pal/src/host/Linux/db_sockets.c#L616)):*
> ```C
>     if (ret < 0) {
> 	    ret = unix_to_pal_error(ret);
> 	    goto failed;
> ```

Please replace tabs with 4 spaces in these two lines.

**Review by sahason — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2678)* status: 0 of 1 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2678#-Miu9YhaDauSy_PmYdvt:-Miw71YLBveerV8DviA7:bellh0d) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

From what I see, Linux-SGX PAL already has this logic of getting the port and assigning it to the relevant `addr` data struct. Is my understanding correct? The only place where this was missing is this UDP-bind function?
</blockquote></details>

Yes, the issue is not seen with graphene-sgx.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2678#-Miu8DQFDfWVzILUU5NB:-Miw7LxMCoVGWLunZbSj:b-xjcnd5) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you enable `sendmmsg01` (and potentially `sendmsg01`) LTP test now, with this fix? For this, you need to remove the following lines in the LTP config: https://github.com/oscarlab/graphene/blob/master/LibOS/shim/test/ltp/ltp.cfg#L1892-L1894
</blockquote></details>

I don't see EINVAL error with sendmmsg anymore with this fix and sendmmsg is working fine. However, the following recvmmsg() failed with EOPNOTSUPP (95) as the timeout parameter is unsupported in graphene https://github.com/oscarlab/graphene/issues/753. 

Regarding sendmsg01 the error is not relevant `ip/ipconfig failed to bring up loop back device`.

---
___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/oscarlab/graphene/2678#-Miu8QXL1D87c9FzTwQu):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would suggest a rewording like this:
```
[Pal/Linux] Assign an ephemeral port if port 0 was specified in `udp_bind`

This is already done in `tcp_listen` via a call to `getsockname()`. Do the same
for UDP sockets.
```
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_sockets.c, line 616 at r1](https://reviewable.io/reviews/oscarlab/graphene/2678#-Miu82ly2TE0oPGMS1tw:-Miw55nd2WCMkeeYsycA:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4c96b186e0100ba21068b44a24446c73000841ea/Pal/src/host/Linux/db_sockets.c#L616)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please replace tabs with 4 spaces in these two lines.
</blockquote></details>

Done.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2678)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @sahason)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2678#-Miu8DQFDfWVzILUU5NB:-Miz-JvE2F5kMifpzBIU:biamwau) (no related file):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

I don't see EINVAL error with sendmmsg anymore with this fix and sendmmsg is working fine. However, the following recvmmsg() failed with EOPNOTSUPP (95) as the timeout parameter is unsupported in graphene https://github.com/oscarlab/graphene/issues/753. 

Regarding sendmsg01 the error is not relevant `ip/ipconfig failed to bring up loop back device`.
</blockquote></details>

OK, so the `sendmmsg01` now fails because it uses a `recvmmsg(timeout)` which is unsupported. Could you update the comment then: https://github.com/oscarlab/graphene/blob/master/LibOS/shim/test/ltp/ltp.cfg#L1892. Please write something like `# uses recvmmsg(timeout) but timeout is unsupported in Graphene`.

---
___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/oscarlab/graphene/2678#-Miu8QXL1D87c9FzTwQu):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You changed it in the `fixup` commit which doesn't really work (fixup commit messages are discarded by git during rebase).

Please do a proper `git rebase` and rewrite the main (and only) commit's message.

**Review by sahason — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2678)* status: 1 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/graphene/2678#-Miu8DQFDfWVzILUU5NB:-Mj-tZ39D-iwSARvtsYn:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

OK, so the `sendmmsg01` now fails because it uses a `recvmmsg(timeout)` which is unsupported. Could you update the comment then: https://github.com/oscarlab/graphene/blob/master/LibOS/shim/test/ltp/ltp.cfg#L1892. Please write something like `# uses recvmmsg(timeout) but timeout is unsupported in Graphene`.
</blockquote></details>

Done.

---
___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/graphene/2678#-Miu8QXL1D87c9FzTwQu):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You changed it in the `fixup` commit which doesn't really work (fixup commit messages are discarded by git during rebase).

Please do a proper `git rebase` and rewrite the main (and only) commit's message.
</blockquote></details>

Done.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2678)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2678)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

**Comment by dimakuv** [comment]
This PR was transferred to https://github.com/gramineproject/gramine/pull/76. Closing here.

**Pull request closed without merging**
