### PR TITLE
[GSC] Add dockerfile and manifest for OpenVINO benchmark

### PR DESCRIPTION
**Pull request by sahason**
Signed-off-by: Sonali Saha <sonali.saha@intel.com>

## Description of the changes 
Examples to run OpenVINO benchmark with GSC.

## How to test this PR? 
Please follow steps present at Tools/gsc/test/openvino_benchmark/README.md

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2580)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2580)* status: 0 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @sahason)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2580#-MgeyyUx1vqnt4zpbU4-:-MgeyyV0043g2z2Po6JR:b-q37f4b) (no related file):*
I have the exact same comments/suggestions as for #2571.

---
___
*[Tools/gsc/test/ubuntu18.04-openvino.dockerfile, line 59 at r1](https://reviewable.io/reviews/oscarlab/graphene/2580#-Mgeyqk36QSMnjeMjAKM:-Mgeyqk36QSMnjeMjAKN:b-vq2yrh) ([raw file](https://github.com/oscarlab/graphene/blob/6528f57c72ad9951bcaeca45d5712610c905477c/Tools/gsc/test/ubuntu18.04-openvino.dockerfile#L59)):*
> ```Dockerfile
> RUN echo "source /opt/intel/openvino_2021/bin/setupvars.sh" | tee -a /root/.bashrc
> 
> CMD ["/bin/bash"]
> ```

Why do you start `bash` and only afterwards you start actual OpenVINO app `benchmark_app`?

**Review by sahason — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2580)* status: 0 of 4 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2580#-MgeyyUx1vqnt4zpbU4-:-MgnWx5A4hH3kaNbkuve:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I have the exact same comments/suggestions as for #2571.
</blockquote></details>

Done.

---
___
*[Tools/gsc/test/ubuntu18.04-openvino.dockerfile, line 59 at r1](https://reviewable.io/reviews/oscarlab/graphene/2580#-Mgeyqk36QSMnjeMjAKM:-MgnVykL2vkHtHEnkoiH:b-ccg4v5) ([raw file](https://github.com/oscarlab/graphene/blob/6528f57c72ad9951bcaeca45d5712610c905477c/Tools/gsc/test/ubuntu18.04-openvino.dockerfile#L59)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you start `bash` and only afterwards you start actual OpenVINO app `benchmark_app`?
</blockquote></details>

I initially wrote this way such that it can run any application other than benchmark_app also. I have changed this to benchmark_app only in current commit as the main focus is on benchmarking. For README link I have used https://github.com/sahason/graphene/blob/ov_benchmark/Examples/openvino_benchmark/README.md for now. Once this is merged I will update the link from master.

**Comment by sahason** [comment]
@mkow I have addressed review comments. Please provide your inputs. If everything looks fine request to approve this PR.

**Review by sahason — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2580)* status: 1 of 4 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2580#-Mi7Bq438FBpuY4IHZ8o:-MiZwLQr4dAChnwWD1dI:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`[GSC] Add dockerfile and manifest file for openvino benchmark.` -> `[GSC] Add dockerfile and manifest for OpenVINO benchmark`
</blockquote></details>

Done.

---
___
*[Tools/gsc/Examples/openvino_benchmark/README.md, line 9 at r2](https://reviewable.io/reviews/oscarlab/graphene/2580#-Mi7COyb0-MWkeoh1Y4_:-MiXaEz04tNSF_VQIELV:b-lpj1wa) ([raw file](https://github.com/oscarlab/graphene/blob/46a14a3721fabaaab44a1f1f3b1d9e0d2c66d585/Tools/gsc/Examples/openvino_benchmark/README.md#L9)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

These shell listing are very hard to read, please reformat them and use Bash syntax highlighting.
</blockquote></details>

I have highlighted using bahs syntax.
Please find the explanation for -m option below.
-m model/<public | intel>/<model_dir>/<INT8 | FP16 | FP32>/<model_xml_file>

The model files are downloaded in different locations based on the model name and precision.

The directory structure is as follows.
model
|_____
public/intel
|__________
model_dir
|___________
INT8/FP16/FP32
|______________
model xml file
___
*[Tools/gsc/Examples/openvino_benchmark/ubuntu18.04-openvino.dockerfile, line 1 at r2](https://reviewable.io/reviews/oscarlab/graphene/2580#-Mi7CeN4AVcUy4x5neZB:-MiX8rFk1Bqg9xc7dysk:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/46a14a3721fabaaab44a1f1f3b1d9e0d2c66d585/Tools/gsc/Examples/openvino_benchmark/ubuntu18.04-openvino.dockerfile#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> From
> ```

In all other places you used uppercase letters for Docker commands, please unify.
</blockquote></details>

Done.
___
*[Tools/gsc/Examples/openvino_benchmark/ubuntu18.04-openvino.dockerfile, line 3 at r2](https://reviewable.io/reviews/oscarlab/graphene/2580#-Mi7DGGqEvPoTWip9LdP:-MiX8wvJBZ-5VKsnqas_:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/46a14a3721fabaaab44a1f1f3b1d9e0d2c66d585/Tools/gsc/Examples/openvino_benchmark/ubuntu18.04-openvino.dockerfile#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

How does this work? You aren't using `DEBIAN_FRONTEND` variable anywhere below?
</blockquote></details>

Done.
___
*[Tools/gsc/Examples/openvino_benchmark/ubuntu18.04-openvino.dockerfile, line 16 at r2](https://reviewable.io/reviews/oscarlab/graphene/2580#-Mi7D_vS5MG5YmWSbvGI:-MiX9OuM0Fu74ETzH2Bm:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/46a14a3721fabaaab44a1f1f3b1d9e0d2c66d585/Tools/gsc/Examples/openvino_benchmark/ubuntu18.04-openvino.dockerfile#L16)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please sort
</blockquote></details>

Done.
___
*[Tools/gsc/Examples/openvino_benchmark/ubuntu18.04-openvino.dockerfile, line 53 at r2](https://reviewable.io/reviews/oscarlab/graphene/2580#-Mi7EHiRBN1tcWD2UPi_:-MiXSz2B9rNRXSzRYbwH:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/46a14a3721fabaaab44a1f1f3b1d9e0d2c66d585/Tools/gsc/Examples/openvino_benchmark/ubuntu18.04-openvino.dockerfile#L53)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please deduplicate these (e.g. with a shell loop)
</blockquote></details>

Done.
___
*[Tools/gsc/Examples/openvino_benchmark/ubuntu18.04-openvino.dockerfile, line 55 at r2](https://reviewable.io/reviews/oscarlab/graphene/2580#-Mi7EPNx62Sw-VGF-ak9:-MiXBCCy9GJWAjFwLigh:b-e0yrlx) ([raw file](https://github.com/oscarlab/graphene/blob/46a14a3721fabaaab44a1f1f3b1d9e0d2c66d585/Tools/gsc/Examples/openvino_benchmark/ubuntu18.04-openvino.dockerfile#L55)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> ENV LD_LIBRARY_PATH = "
> ```

I don't think this syntax works. See https://docs.docker.com/engine/reference/builder/#env.
</blockquote></details>

This was working though. I have removed spaces surrounding =.
___
*[Tools/gsc/test/ubuntu18.04-openvino.dockerfile, line 59 at r1](https://reviewable.io/reviews/oscarlab/graphene/2580#-Mgeyqk36QSMnjeMjAKM:-MgnYgkz3FabF-tz94Ag:b-7nq1w4) ([raw file](https://github.com/oscarlab/graphene/blob/6528f57c72ad9951bcaeca45d5712610c905477c/Tools/gsc/test/ubuntu18.04-openvino.dockerfile#L59)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

You download a bunch of models, are all of them ran here? Or how does this work?
</blockquote></details>

We can run benchmarking by passing a specific model name in the docker run command.

**Comment by sahason** [comment]
This PR was transferred to https://github.com/gramineproject/gsc/pull/18. Closing here.

**Pull request closed without merging**
