### PR TITLE
[LibOS] Remove unused canary in shim_tcb

### PR DESCRIPTION
**Pull request by mkow**
## Description of the changes 

Just removing some unused code.

We should ping @stefanberger after merging this, he'll probably need analogous change in his port.

Caveat: We probably shouldn't merge it before the build system rewrite, as it changes a file which is incorrectly dep-tracked and only `git clean -dfx` helps.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2494)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2494)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2494#-MdWxXQ277opZ58XDbYZ:-MdWxXQ277opZ58XDbY_:bah0epk) (no related file):*
Let's block until our move to Meson is complete. At that point, we'll need to verify that all auto-generated offset files are correctly dependency-tracked and rebuilt when we have changes like in this PR.

---

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2494)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

**Review by stefanberger — COMMENTED** [review]
Thanks for letting me know. There's a static assert in the code (at least ppc64) that alerted me on the changes. I am already applying it...

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2494#-:-Mee8pj7Dq3ODfj7A8cs:b-lko8ru)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

**Comment by mkow** [comment]
Migrated to https://github.com/gramineproject/gramine/pull/1.

**Pull request closed without merging**
