### PR TITLE
[GSC] Update GSC to support 20.04 Ubuntu containers

### LINKED ISSUE #2612: Ubuntu 20.04 support for GSC
Currently GSC supports Ubuntu 18.04 as base OS. Can you please add support for Ubuntu 20.04 also?

### PR DESCRIPTION
**Pull request by aneessahib**
## Description of the changes 
Two changes here. 
1. Updates GSC to support 20.04 Ubuntu. 
2. Point GSC tests to master.

Fixes #2612 
## How to test this PR? 

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2670)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2670)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib)

___
*[Tools/gsc/test/Makefile, line 39 at r1](https://reviewable.io/reviews/oscarlab/graphene/2670#-MiWfLfM6FT_szf9iO73:-MiWfLfN0CDdZxRAtiRI:b-mnn64g) ([raw file](https://github.com/oscarlab/graphene/blob/c3d978bc63cb36dd3ab1b7d4a6d4b73ed7b97235/Tools/gsc/test/Makefile#L39)):*
> ```Makefile
> 
> config-%.yaml:
> 	echo "Distro: \"$(subst $(DISTRO_PREFIX),$(DISTRO_SUFFIX):,$(*))\"" > config-$*.yaml
> ```

What does this do? Where do get `DISTRO_SUFFIX` from?
___
*[Tools/gsc/templates/Dockerfile.compile.template, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/2670#-MiWg84J2ohjhwAS4pVD:-MiWg84J2ohjhwAS4pVE:b9asuxc) ([raw file](https://github.com/oscarlab/graphene/blob/c3d978bc63cb36dd3ab1b7d4a6d4b73ed7b97235/Tools/gsc/templates/Dockerfile.compile.template#L1)):*
> ```
> FROM {{Distro}} AS graphene
> ```

Can you add a comment here that currently tested base OS images are ubuntu18.04 and ubuntu 20.04

**Review by aneessahib — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2670)* status: 4 of 5 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Tools/gsc/test/Makefile, line 39 at r1](https://reviewable.io/reviews/oscarlab/graphene/2670#-MiWfLfM6FT_szf9iO73:-MiX3zxv86Ht26YN0lpo:bk2n0vj) ([raw file](https://github.com/oscarlab/graphene/blob/c3d978bc63cb36dd3ab1b7d4a6d4b73ed7b97235/Tools/gsc/test/Makefile#L39)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What does this do? Where do get `DISTRO_SUFFIX` from?
</blockquote></details>

Horrible bug! A last minute correction on the name not done properly. The correct one is ``` "$(subst $(DISTRO_PREFIX),$(DISTRO_PREFIX):,$(*))\"" ``` This actually writes the Distro information to the config.yaml file, in the format ```distro:version```  (eg. ```ubuntu:18.04```). Which can then be read as is from the compile template as ```{{Distro}}``` .  What was already there would have written ```ubuntu18.04``` instead.
And i have hard coded the DISTRO_PREFIX to be ```ubuntu``` in the Makefile.  Not very proud of it but anything else fancy would require a lot bandaids in the Makefile.
___
*[Tools/gsc/templates/Dockerfile.compile.template, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/2670#-MiWg84J2ohjhwAS4pVD:-MiX3yO2647s3cWCcR_G:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/c3d978bc63cb36dd3ab1b7d4a6d4b73ed7b97235/Tools/gsc/templates/Dockerfile.compile.template#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you add a comment here that currently tested base OS images are ubuntu18.04 and ubuntu 20.04
</blockquote></details>

Done.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2670)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2670#-MiaWNjUBu4f2gEcFO7_:-MiaWNjUBu4f2gEcFO7a:bm40b0f) (no related file):*
Aren't you supposed to also change this: https://github.com/aneessahib/graphene/blob/aad1c6d61c635abf9574a9151f26d256bc70edd8/Tools/gsc/config.yaml.template#L3

from `Distro: "ubuntu18.04"` to `Distro: "ubuntu:18.04"`

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2670#-MiaWWsL6-h9yUoxlotM:-MiaWWsL6-h9yUoxlotN:b-gll1ri) (no related file):*
Also, this comment is wrong now: https://github.com/aneessahib/graphene/blob/aad1c6d61c635abf9574a9151f26d256bc70edd8/Tools/gsc/config.yaml.template#L1

---
___
*[Tools/gsc/test/Makefile, line 39 at r1](https://reviewable.io/reviews/oscarlab/graphene/2670#-MiWfLfM6FT_szf9iO73:-MiaXrez3TXcDNFx0HBp:bsvd394) ([raw file](https://github.com/oscarlab/graphene/blob/c3d978bc63cb36dd3ab1b7d4a6d4b73ed7b97235/Tools/gsc/test/Makefile#L39)):*
<details><summary><i>Previously, aneessahib wrote…</i></summary><blockquote>

Horrible bug! A last minute correction on the name not done properly. The correct one is ``` "$(subst $(DISTRO_PREFIX),$(DISTRO_PREFIX):,$(*))\"" ``` This actually writes the Distro information to the confiy.yaml file, in the format ```distro:version```  (eg. ```ubuntu:18.04```). Which can then be read as is from the compile template as ```{{Distro}}``` .  What was already there would have written ```ubuntu18.04``` instead.
And i have hard coded the DISTRO_PREFIX to be ```ubuntu``` in the Makefile.  Not very proud of it but anything else fancy would require a lot bandaids in the Makefile.
</blockquote></details>

I'm a bit confused how this works. Does `make DISTRIBUTION=ubuntu18.04` still work correctly? What about `make DISTRIBUTION=ubuntu20.04`?

In general, I definitely want to remove this Makefile, it's unreadable...
___
*[Tools/gsc/templates/Dockerfile.compile.template, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/2670#-MiWg84J2ohjhwAS4pVD:-MiaVoJI-53aCU7xVVAO:b-81j9ks) ([raw file](https://github.com/oscarlab/graphene/blob/c3d978bc63cb36dd3ab1b7d4a6d4b73ed7b97235/Tools/gsc/templates/Dockerfile.compile.template#L1)):*
<details><summary><i>Previously, aneessahib wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see the comment. I only see the comment in the commit message, but I would prefer to see it in this Dockerfile.

**Review by aneessahib — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2670)* status: 4 of 7 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2670#-MiaWNjUBu4f2gEcFO7_:-Mif_mg70vh7J7NvXEmW:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Aren't you supposed to also change this: https://github.com/aneessahib/graphene/blob/aad1c6d61c635abf9574a9151f26d256bc70edd8/Tools/gsc/config.yaml.template#L3

from `Distro: "ubuntu18.04"` to `Distro: "ubuntu:18.04"`
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2670#-MiaWWsL6-h9yUoxlotM:-Mif_oPg5EPLUANPxIaS:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Also, this comment is wrong now: https://github.com/aneessahib/graphene/blob/aad1c6d61c635abf9574a9151f26d256bc70edd8/Tools/gsc/config.yaml.template#L1
</blockquote></details>

Done.

---
___
*[Tools/gsc/test/Makefile, line 39 at r1](https://reviewable.io/reviews/oscarlab/graphene/2670#-MiWfLfM6FT_szf9iO73:-MifZUDr7PC8QscuEQ_r:bkvylbj) ([raw file](https://github.com/oscarlab/graphene/blob/c3d978bc63cb36dd3ab1b7d4a6d4b73ed7b97235/Tools/gsc/test/Makefile#L39)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm a bit confused how this works. Does `make DISTRIBUTION=ubuntu18.04` still work correctly? What about `make DISTRIBUTION=ubuntu20.04`?

In general, I definitely want to remove this Makefile, it's unreadable...
</blockquote></details>

only ```make DISTRIBUTION=ubuntu18.04``` will continue to work.  But 20.04 support is too much work on this Makefile (if you see the even targets are currently hardcoded for 18.04).  So we can limit the tests to 18.04 only for now.
___
*[Tools/gsc/templates/Dockerfile.compile.template, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/2670#-MiWg84J2ohjhwAS4pVD:-MifZKhfAoHMVnR7zE48:b-6d91lb) ([raw file](https://github.com/oscarlab/graphene/blob/c3d978bc63cb36dd3ab1b7d4a6d4b73ed7b97235/Tools/gsc/templates/Dockerfile.compile.template#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't see the comment. I only see the comment in the commit message, but I would prefer to see it in this Dockerfile.
</blockquote></details>

Done. Have added equivalent comments in couple of other places as well (manpages/gsc.rst and config.yaml.template)

**Comment by aneessahib** [comment]
@dimakuv  i have also clarified in the ```gsc/test/README``` that the tests only supports 18.04.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2670)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)

___
*[Documentation/manpages/gsc.rst, line 303 at r3](https://reviewable.io/reviews/oscarlab/graphene/2670#-Miz1_6d2oiPCqagCmk4:-Miz1_6e1PZyN0mU16lO:b-6dwfd5) ([raw file](https://github.com/oscarlab/graphene/blob/868ad28d85eb7d5990d5b91013942e9b8eb853ae/Documentation/manpages/gsc.rst#L303)):*
> ```reStructuredText
> 
>    Defines Linux distribution to be used to build Graphene in. Currently tested
>    distros are ubuntu 18.04 and ubuntu 20.04. Default value is ``ubuntu18.04``.
> ```

Ubuntu with capital letter (2x)
___
*[Tools/gsc/config.yaml.template, line 1 at r3](https://reviewable.io/reviews/oscarlab/graphene/2670#-Miz10Vz1Lreu2z0MZBZ:-Miz10W-6kU78OrOBMEA:bcdrj37) ([raw file](https://github.com/oscarlab/graphene/blob/868ad28d85eb7d5990d5b91013942e9b8eb853ae/Tools/gsc/config.yaml.template#L1)):*
> ```
> # Specify the OS distro in the below format as shown for ubuntu 18.04. Currently tested distros are ubuntu 18.04 and ubuntu 20.04.
> ```

Please wrap this line into 100 char limit.

Actually, you can just shorten this comment to:
```
# Specify the OS distro. Currently tested distros are Ubuntu 18.04 and Ubuntu 20.04.
```
___
*[Tools/gsc/test/README.rst, line 18 at r3](https://reviewable.io/reviews/oscarlab/graphene/2670#-Miz1iL478GZ8AJg2nAD:-Miz1iL478GZ8AJg2nAE:b-r46oim) ([raw file](https://github.com/oscarlab/graphene/blob/868ad28d85eb7d5990d5b91013942e9b8eb853ae/Tools/gsc/test/README.rst#L18)):*
> ```reStructuredText
> ``<distro>-<image-name>.manifest`` where ``<distro>`` specifies the underlying
> Linux distribution and ``<image-name>`` specifies the test case. The tests
> currently supports ubuntu 18.04 distribution only. The manifest
> ```

`supports` -> `support`

`ubuntu` -> `Ubuntu`
___
*[Tools/gsc/templates/Dockerfile.compile.template, line 2 at r3](https://reviewable.io/reviews/oscarlab/graphene/2670#-Miz1Mga8s5mP_fXm34W:-Miz1Mga8s5mP_fXm34X:bluascp) ([raw file](https://github.com/oscarlab/graphene/blob/868ad28d85eb7d5990d5b91013942e9b8eb853ae/Tools/gsc/templates/Dockerfile.compile.template#L2)):*
> ```
> FROM {{Distro}} AS graphene
> # Currently tested base OS images are ubuntu 18.04 and ubuntu 20.04
> ```

Looks a bit weird. Typically comments are placed before the line of code. In this case, I would change to this:
```
# Currently tested base OS images (distros) are Ubuntu 18.04 and Ubuntu 20.04
FROM {{Distro}} AS graphene
```

**Review by aneessahib — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2670)* status: 4 of 8 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Documentation/manpages/gsc.rst, line 303 at r3](https://reviewable.io/reviews/oscarlab/graphene/2670#-Miz1_6d2oiPCqagCmk4:-MizAiLz7vjOSw5ntc9K:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/868ad28d85eb7d5990d5b91013942e9b8eb853ae/Documentation/manpages/gsc.rst#L303)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ubuntu with capital letter (2x)
</blockquote></details>

Done.
___
*[Tools/gsc/config.yaml.template, line 1 at r3](https://reviewable.io/reviews/oscarlab/graphene/2670#-Miz10Vz1Lreu2z0MZBZ:-MizAlzXEbuRNjmbrX6p:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/868ad28d85eb7d5990d5b91013942e9b8eb853ae/Tools/gsc/config.yaml.template#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please wrap this line into 100 char limit.

Actually, you can just shorten this comment to:
```
# Specify the OS distro. Currently tested distros are Ubuntu 18.04 and Ubuntu 20.04.
```
</blockquote></details>

Done.
___
*[Tools/gsc/test/README.rst, line 18 at r3](https://reviewable.io/reviews/oscarlab/graphene/2670#-Miz1iL478GZ8AJg2nAD:-MizArEs8FVL-LQKqA6x:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/868ad28d85eb7d5990d5b91013942e9b8eb853ae/Tools/gsc/test/README.rst#L18)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`supports` -> `support`

`ubuntu` -> `Ubuntu`
</blockquote></details>

Done.
___
*[Tools/gsc/templates/Dockerfile.compile.template, line 2 at r3](https://reviewable.io/reviews/oscarlab/graphene/2670#-Miz1Mga8s5mP_fXm34W:-MizAombDzVqsNwq9A_q:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/868ad28d85eb7d5990d5b91013942e9b8eb853ae/Tools/gsc/templates/Dockerfile.compile.template#L2)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Looks a bit weird. Typically comments are placed before the line of code. In this case, I would change to this:
```
# Currently tested base OS images (distros) are Ubuntu 18.04 and Ubuntu 20.04
FROM {{Distro}} AS graphene
```
</blockquote></details>

Done.

**Review by dimakuv — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2670)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

**Comment by dimakuv** [comment]
This PR was transferred to https://github.com/gramineproject/gsc/pull/14. Closing here.

**Pull request closed without merging**
